void _puts_recursion(char *s);
int _putchar(char c);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int _sqrt_find(int n, int root);
int _sqrt_recursion(int n);
int is_prime_number(int n);
int _isprime(unsigned int num, unsigned int operand);
int is_palindrome(char *s);
